### ISSUE TITLE
Release emacs-bazel-mode to MELPA

### ISSUE THREAD

**Issue by oxddr** [bazelbuild/emacs-bazel-mode#13]
Can we have this package release to MELPA so it can be easily installed? 

I've never done it myself, but I'd be happy to help if there is anything I can do to make it happen.

**Comment by oxddr** [comment]
Actually it seems no that difficult at all: https://github.com/melpa/melpa#recipe-format. I'll send a PR later this week to add bazel-mode there unless there are any objections from maintainers.

**Comment by phst** [comment]
No objections from me, thanks!

**Comment by laurentlb** [comment]
@oxddr Do you still plan to do it?

**Comment by oxddr** [comment]
I'll try to have a look into that this week.

**Comment by jkaye2012** [comment]
I was looking into using this package last night and came across this issue. I've submitted the recipe to MELPA; I was unable to run their linter so I will follow up with them to hopefully get this submitted soon.

**Comment by oxddr** [comment]
Thanks @jkaye2012!

**Comment by cclark-splash** [comment]
This package is on MELPA: https://melpa.org/#/bazel. This issue can be closed.
